name: Coverage test - CodeClimate
on: [push, workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Download and Verify CodeClimate reporter binaries
      run: |
        curl -L -O https://codeclimate.com/downloads/test-reporter/test-reporter-0.10.1-darwin-amd64
        curl -L -O https://codeclimate.com/downloads/test-reporter/test-reporter-0.10.1-darwin-amd64.sha256
        grep test-reporter-0.10.1-darwin-amd64  test-reporter-${VERSION}-darwin-amd64.sha256 | shasum -a 256 -c -      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    
    - name: Analysing the code with coverage
      run: |
        ./cc-test-reporter before-build
        coverage run -m unittest discover
        coverage xml --omit='env/*,tests/*'
        ./cc-test-reporter format-coverage -t coverage.py
        ./cc-test-reporter upload-coverage
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER }}


